// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX_zm3_hgIMnNizHWs-7xRAlbSz15bl5Q',
    appId: '1:529183449840:web:a3e83b7721db62f20d1835',
    messagingSenderId: '529183449840',
    projectId: 'der3hediety',
    authDomain: 'der3hediety.firebaseapp.com',
    storageBucket: 'der3hediety.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE9vpu7_WkB2ZygtnwxbGp9zjwlVsZI5c',
    appId: '1:529183449840:android:15623b4fa9a9d5950d1835',
    messagingSenderId: '529183449840',
    projectId: 'der3hediety',
    storageBucket: 'der3hediety.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6y4eQELmzgIXVtU4SJrCVfzlzyg10I7E',
    appId: '1:529183449840:ios:a6d7bcb94c5392860d1835',
    messagingSenderId: '529183449840',
    projectId: 'der3hediety',
    storageBucket: 'der3hediety.firebasestorage.app',
    iosBundleId: 'com.example.hediety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6y4eQELmzgIXVtU4SJrCVfzlzyg10I7E',
    appId: '1:529183449840:ios:a6d7bcb94c5392860d1835',
    messagingSenderId: '529183449840',
    projectId: 'der3hediety',
    storageBucket: 'der3hediety.firebasestorage.app',
    iosBundleId: 'com.example.hediety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX_zm3_hgIMnNizHWs-7xRAlbSz15bl5Q',
    appId: '1:529183449840:web:3a5f5077578471840d1835',
    messagingSenderId: '529183449840',
    projectId: 'der3hediety',
    authDomain: 'der3hediety.firebaseapp.com',
    storageBucket: 'der3hediety.firebasestorage.app',
  );
}
